services:

  registration-micro:
    container_name: registration_microservice

    build:
      context: ./Registration_Microservice
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001

  login-micro:
    container_name: authentication_microservice

    build:
      context: ./Authentication_Microservice
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3002:3002"

    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3002